# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aimad/Desktop/projects/fhe_compiler/fheco_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aimad/Desktop/projects/fhe_compiler/fheco_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aimad/Desktop/projects/fhe_compiler/fheco_project/CMakeFiles /home/aimad/Desktop/projects/fhe_compiler/fheco_project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aimad/Desktop/projects/fhe_compiler/fheco_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FHECO_PROJECT

# Build rule for target.
FHECO_PROJECT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FHECO_PROJECT
.PHONY : FHECO_PROJECT

# fast build rule for target.
FHECO_PROJECT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FHECO_PROJECT.dir/build.make CMakeFiles/FHECO_PROJECT.dir/build
.PHONY : FHECO_PROJECT/fast

#=============================================================================
# Target rules for targets named dsl

# Build rule for target.
dsl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsl
.PHONY : dsl

# fast build rule for target.
dsl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/build
.PHONY : dsl/fast

#=============================================================================
# Target rules for targets named ir

# Build rule for target.
ir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ir
.PHONY : ir

# fast build rule for target.
ir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/build
.PHONY : ir/fast

benchmarks/test1.o: benchmarks/test1.cpp.o
.PHONY : benchmarks/test1.o

# target to build an object file
benchmarks/test1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FHECO_PROJECT.dir/build.make CMakeFiles/FHECO_PROJECT.dir/benchmarks/test1.cpp.o
.PHONY : benchmarks/test1.cpp.o

benchmarks/test1.i: benchmarks/test1.cpp.i
.PHONY : benchmarks/test1.i

# target to preprocess a source file
benchmarks/test1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FHECO_PROJECT.dir/build.make CMakeFiles/FHECO_PROJECT.dir/benchmarks/test1.cpp.i
.PHONY : benchmarks/test1.cpp.i

benchmarks/test1.s: benchmarks/test1.cpp.s
.PHONY : benchmarks/test1.s

# target to generate assembly for a file
benchmarks/test1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FHECO_PROJECT.dir/build.make CMakeFiles/FHECO_PROJECT.dir/benchmarks/test1.cpp.s
.PHONY : benchmarks/test1.cpp.s

src/dsl/ciphertext.o: src/dsl/ciphertext.cpp.o
.PHONY : src/dsl/ciphertext.o

# target to build an object file
src/dsl/ciphertext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/ciphertext.cpp.o
.PHONY : src/dsl/ciphertext.cpp.o

src/dsl/ciphertext.i: src/dsl/ciphertext.cpp.i
.PHONY : src/dsl/ciphertext.i

# target to preprocess a source file
src/dsl/ciphertext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/ciphertext.cpp.i
.PHONY : src/dsl/ciphertext.cpp.i

src/dsl/ciphertext.s: src/dsl/ciphertext.cpp.s
.PHONY : src/dsl/ciphertext.s

# target to generate assembly for a file
src/dsl/ciphertext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/ciphertext.cpp.s
.PHONY : src/dsl/ciphertext.cpp.s

src/dsl/plaintext.o: src/dsl/plaintext.cpp.o
.PHONY : src/dsl/plaintext.o

# target to build an object file
src/dsl/plaintext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/plaintext.cpp.o
.PHONY : src/dsl/plaintext.cpp.o

src/dsl/plaintext.i: src/dsl/plaintext.cpp.i
.PHONY : src/dsl/plaintext.i

# target to preprocess a source file
src/dsl/plaintext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/plaintext.cpp.i
.PHONY : src/dsl/plaintext.cpp.i

src/dsl/plaintext.s: src/dsl/plaintext.cpp.s
.PHONY : src/dsl/plaintext.s

# target to generate assembly for a file
src/dsl/plaintext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/plaintext.cpp.s
.PHONY : src/dsl/plaintext.cpp.s

src/dsl/scalar.o: src/dsl/scalar.cpp.o
.PHONY : src/dsl/scalar.o

# target to build an object file
src/dsl/scalar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/scalar.cpp.o
.PHONY : src/dsl/scalar.cpp.o

src/dsl/scalar.i: src/dsl/scalar.cpp.i
.PHONY : src/dsl/scalar.i

# target to preprocess a source file
src/dsl/scalar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/scalar.cpp.i
.PHONY : src/dsl/scalar.cpp.i

src/dsl/scalar.s: src/dsl/scalar.cpp.s
.PHONY : src/dsl/scalar.s

# target to generate assembly for a file
src/dsl/scalar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dsl.dir/build.make CMakeFiles/dsl.dir/src/dsl/scalar.cpp.s
.PHONY : src/dsl/scalar.cpp.s

src/ir/dag.o: src/ir/dag.cpp.o
.PHONY : src/ir/dag.o

# target to build an object file
src/ir/dag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/dag.cpp.o
.PHONY : src/ir/dag.cpp.o

src/ir/dag.i: src/ir/dag.cpp.i
.PHONY : src/ir/dag.i

# target to preprocess a source file
src/ir/dag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/dag.cpp.i
.PHONY : src/ir/dag.cpp.i

src/ir/dag.s: src/ir/dag.cpp.s
.PHONY : src/ir/dag.s

# target to generate assembly for a file
src/ir/dag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/dag.cpp.s
.PHONY : src/ir/dag.cpp.s

src/ir/program.o: src/ir/program.cpp.o
.PHONY : src/ir/program.o

# target to build an object file
src/ir/program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/program.cpp.o
.PHONY : src/ir/program.cpp.o

src/ir/program.i: src/ir/program.cpp.i
.PHONY : src/ir/program.i

# target to preprocess a source file
src/ir/program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/program.cpp.i
.PHONY : src/ir/program.cpp.i

src/ir/program.s: src/ir/program.cpp.s
.PHONY : src/ir/program.s

# target to generate assembly for a file
src/ir/program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/program.cpp.s
.PHONY : src/ir/program.cpp.s

src/ir/term.o: src/ir/term.cpp.o
.PHONY : src/ir/term.o

# target to build an object file
src/ir/term.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/term.cpp.o
.PHONY : src/ir/term.cpp.o

src/ir/term.i: src/ir/term.cpp.i
.PHONY : src/ir/term.i

# target to preprocess a source file
src/ir/term.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/term.cpp.i
.PHONY : src/ir/term.cpp.i

src/ir/term.s: src/ir/term.cpp.s
.PHONY : src/ir/term.s

# target to generate assembly for a file
src/ir/term.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ir.dir/build.make CMakeFiles/ir.dir/src/ir/term.cpp.s
.PHONY : src/ir/term.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FHECO_PROJECT"
	@echo "... dsl"
	@echo "... ir"
	@echo "... benchmarks/test1.o"
	@echo "... benchmarks/test1.i"
	@echo "... benchmarks/test1.s"
	@echo "... src/dsl/ciphertext.o"
	@echo "... src/dsl/ciphertext.i"
	@echo "... src/dsl/ciphertext.s"
	@echo "... src/dsl/plaintext.o"
	@echo "... src/dsl/plaintext.i"
	@echo "... src/dsl/plaintext.s"
	@echo "... src/dsl/scalar.o"
	@echo "... src/dsl/scalar.i"
	@echo "... src/dsl/scalar.s"
	@echo "... src/ir/dag.o"
	@echo "... src/ir/dag.i"
	@echo "... src/ir/dag.s"
	@echo "... src/ir/program.o"
	@echo "... src/ir/program.i"
	@echo "... src/ir/program.s"
	@echo "... src/ir/term.o"
	@echo "... src/ir/term.i"
	@echo "... src/ir/term.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

