#pragma once
#include "fhecompiler/fhecompiler.hpp"

int test1_frontend();
int test2_frontend();
int test3_frontend();
int test4_frontend();
int test5_frontend();
int test6_frontend();
int test7_frontend();
int test8_frontend();
int test9_frontend();
int test10_frontend();
int test11_frontend();
int test12_frontend();
int test13_frontend();
int test14_frontend();
int test15_frontend();
int test16_frontend();
int test17_frontend();
int test18_frontend();
int test19_frontend();
int test20_frontend();
int test21_frontend();
